event-world: ""
players-per-team: 10
queue-countdown-seconds: 120
vote-duration-seconds: 30
base-separation-blocks: 500
spawn-y: 256
paste-anchor-x: 0
paste-anchor-z: 0
paste-y: 64

match-duration-seconds: 1500
countdown-seconds: 10
respawn-delay-seconds: 10
depth-sample-interval-ticks: 20

breach-materials:
  - OBSIDIAN

draw-on-equal-depth: true
lock-notify-cooldown-ms: 2000

worldedit-paste-offset:
  add-worldedit-offset: true
  extra-x: 0
  extra-y: 0
  extra-z: 0

factions:
  base-claim-method: isBaseClaim
  source-world: world
